// // 'use client'
// import type { Metadata } from "next";
// import Image from "next/image";
// import Link from "next/link";
// import localFont from "next/font/local";
// import "./globals.css";
// import { NavLinks } from "./globals/NavLinks/NavLinks";
// // import { useEffect } from "react";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Add",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//     // useEffect(() => {
//     //   alert("Home");
//     // }, []);
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
//           <NavLinks />
//           <main className="flex flex-col gap-8 items-center sm:items-start max-w-md">
//             {children}
//           </main>
//           <footer className="flex gap-6 flex-wrap items-center justify-center">
//             <Link
//               href="/"
//               className="flex items-center gap-2 hover:underline hover:underline-offset-4"
//             >
//               Home
//             </Link>
//             <Link
//               className="flex items-center gap-2 hover:underline hover:underline-offset-4"
//               href="/contact-us"
//               rel="noopener noreferrer"
//             >
//               <Image
//                 aria-hidden
//                 src="/file.svg"
//                 alt="File icon"
//                 width={16}
//                 height={16}
//               />
//               Contact us
//             </Link>
//             <Link
//               className="flex items-center gap-2 hover:underline hover:underline-offset-4"
//               href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               <Image
//                 aria-hidden
//                 src="/window.svg"
//                 alt="Window icon"
//                 width={16}
//                 height={16}
//               />
//               Examples
//             </Link>
//             <Link
//               className="flex items-center gap-2 hover:underline hover:underline-offset-4"
//               href="https://nextjs.org?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
//               target="_blank"
//               rel="noopener noreferrer"
//             >
//               <Image
//                 aria-hidden
//                 src="/globe.svg"
//                 alt="Globe icon"
//                 width={16}
//                 height={16}
//               />
//               Go to nextjs.org →
//             </Link>
//           </footer>
//         </div>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/ui/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
